all: 
	python3 -u main.py
clean:
	rm -rf *.o ./exec
	clear
bissec:
	python3 -u bissec.py
cordas:
	python3 -u cordas.py
converter-base:
	python3 -u converter-base.py
interacaoLinear:
	python3 -u interacaoLinear.py
newton: 
	python3 -u newton.py
